name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  PRE_COMMIT_VERSION: "4.0.1"
  PRE_COMMIT_PYTHON_VERSION: "3.12"

jobs:
  precommit:
    name: Precommit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: griceturrble/precommit-checks-action@v1

  test:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # N-4 -> N versions, following Python support schedule
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest
