name: Release to PyPI
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/type-stripper
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build project
        run: uv build

      - name: Publish to PyPI
        run: uv publish
